FROM gradle:8.5-jdk17 AS build

WORKDIR /app
COPY . .

RUN gradle :bot-discord:jar --no-daemon

FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

COPY --from=build /app/bot-discord/build/libs/bot-discord-1.0.0-SNAPSHOT.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
